name: build-deploy
on: [push]
env:
  AWS_REGION: us-east-1
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: { id-token: write, contents: read }
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with: { role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}, aws-region: ${{ env.AWS_REGION }} }
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: '21' }
      - run: mvn -B -pl app-web package -DskipTests
      - run: |
          docker build -t $WEB_IMAGE app-web
          docker push $WEB_IMAGE
      - run: terraform -chdir=iac apply -auto-approve \
             -var="web_image=$WEB_IMAGE" 