name: build-deploy
on:
  push:

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    strategy:
      matrix:
        service: [web, worker]

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region:     ${{ env.AWS_REGION }}

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build Maven project
        run: |
          mvn -B -f image-recognition-aws/app-${{ matrix.service }}/pom.xml \
              package -DskipTests

      - name: Build & push Docker image
        run: |
          docker build -t $ECR_REGISTRY/${{ matrix.service }}:$IMAGE_TAG \
               image-recognition-aws/app-${{ matrix.service }}
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
          docker push $ECR_REGISTRY/${{ matrix.service }}:$IMAGE_TAG

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region:     ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Clean Terraform cache
        working-directory: image-recognition-aws/iac
        run: rm -rf .terraform

      - name: Terraform Init
        working-directory: image-recognition-aws/iac
        run: terraform init

      - name: Terraform Apply
        working-directory: image-recognition-aws/iac
        run: |
          terraform apply -auto-approve \
            -var="web_image=$ECR_REGISTRY/web:$IMAGE_TAG" \
            -var="worker_image=$ECR_REGISTRY/worker:$IMAGE_TAG"